# Build pipeline for Local Agent with Deploy to Devtest Slot
trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  solution: '**/BugTracker.sln'
  buildPlatform: 'Any CPU'
  project: 'BugTracker.csproj'
  buildConfiguration: 'Release'

steps:
# Install NuGet Tools
- task: NuGetToolInstaller@1
  name: NugetToolInstaller

# Restore NuGet Packages
- task: DotNetCoreCLI@2
  name: NugetRestore
  inputs:
    command: restore
    projects: '$(solution)'

# Run Tests
- task: DotNetCoreCLI@2
  name: Tests
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

# Publish project
- task: DotNetCoreCLI@2
  name: Publish
  inputs:
    azureSubscription: 'azuredevops-to-azureresource-service-connection'
    projects: '$(project)'
    command: publish
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  name: PublishBuildArtifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AzureBugTrackerTestProject'
    publishLocation: Container

# Deploy to devtest slot
- task: AzureWebApp@1
  displayName: Deploy ZIP to Devtest slot
  inputs:
    azureSubscription: 'azuredevops-to-azureresource-service-connection'
    appType: webApp
    appName: 'bugtrackerapi20250516235431'
    resourceGroupName: 'FinalProReRe20250306152958ResourceGroup'
    deployToSlotOrASE: true
    slotName: devtest
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
