trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndDeploy
  displayName: 'Build & Deploy to Dev'
  jobs:
  - job: Build
    displayName: 'Build & Test'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=FileSystem
          /p:PublishProtocol=FileSystem
          /p:publishUrl=$(Build.ArtifactStagingDirectory)/publish

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: ArchiveFiles@2
      displayName: 'Archive publish folder to WebApp.zip'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish WebApp.zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
        artifact: 'drop'

  - job: DeployToDev
    displayName: 'Deploy to Dev Slot'
    dependsOn: Build
    steps:
    - download: current
      artifact: drop

    - task: ExtractFiles@1
      displayName: 'Unzip publish output'
      inputs:
        archiveFilePatterns: '$(Pipeline.Workspace)/drop/WebApp.zip'
        destinationFolder: '$(Pipeline.Workspace)/drop/publish'

    - task: AzureWebApp@1
      displayName: 'Deploy to Dev Slot'
      inputs:
        azureSubscription: 'azuredevops-to-azureresource-service-connection'
        appType: 'webApp'
        appName: 'bugtrackerapi20250516235431'
        deployToSlotOrASE: true
        resourceGroupName: 'FinalProReRe20250306152958ResourceGroup'
        slotName: 'devtest'
        package: '$(Pipeline.Workspace)/drop/publish'
        deploymentMethod: 'auto'

- stage: SwapToProd
  displayName: 'Swap Dev → Production'
  dependsOn: BuildAndDeploy
  jobs:
  - deployment: SwapToProduction
    displayName: 'Swap to Production'
    environment: 'ProductionEnv'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            displayName: 'Swap Slots'
            inputs:
              azureSubscription: 'azuredevops-to-azureresource-service-connection'
              action: 'Swap Slots'
              WebAppName: 'BugTrackerApi20250516235431'
              ResourceGroupName: 'FinalProReRe20250306152958ResourceGroup'
              SourceSlot: 'devtest'
              SwapWithProduction: true
