# Build pipeline for Local Agent

trigger:
  branches:
    include:
      - main
    
pool:
  name: 'Default'

variables:
  solution: '**/BugTracker.sln'
  buildPlatform: 'Any CPU'  
  project: 'BugTracker.csproj'
  buildConfiguration: 'Release'

steps: 

#First STep Not Needed If Not Containerized & Self-hosted Agent
#Install and Add to PATH the .NET 8 SDK
#  - task: UseDotNet@2
#    displayName: 'Install .NET 9 SDK'
#    inputs:
#      packageType: 'sdk'
#      version: '9.0.200'

#Install Nuget Tool
  - task: NuGetToolInstaller@1
    name: 'NugetToolInstaller'
    displayName: 'Install Nuget Tools'

#Restore Nuget references    
  - task: DotNetCoreCLI@2
    name: 'NugetRestore'
    displayName: 'Restore Nuget Packages'
    inputs:
      command: 'restore'
      projects: '$(solution)'

#Test building solution    
  - task: DotNetCoreCLI@2
    name: 'Tests'
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'

#Publish project 
  - task: DotNetCoreCLI@2
    name: 'Publish'
    displayName: 'Publish'
    inputs:
      azureSubscription: 'azuredevops-to-azureresource-service-connection'
      projects: $(project)
      command: 'publish'
      publishWebProjects: true
      zipAfterPublish: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      

#Publish Artifact
  - task: PublishBuildArtifacts@1
    name: 'PublishBuildArtifacts'
    displayName: 'Publish Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'AzureBugTrackerTestProject'
      publishLocation: 'Container'